#############################################################################
# Makefile for building: FastSLAM
# Generated by qmake (2.01a) (Qt 4.8.7) on: Fri Mar 19 19:29:34 2021
# Project:  FastSLAM.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile FastSLAM.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Ilibs/eigen3 -Ibuild
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/fastslam_core.cpp \
		src/qcustomplot.cpp \
		src/SLAM_Plot.cpp \
		src/SLAM_Thread.cpp \
		src/fastslam_1.cpp \
		src/fastslam_2.cpp \
		src/ekfslam_1.cpp \
		src/main.cpp \
		src/utils.cpp build/moc_qcustomplot.cpp \
		build/moc_SLAM_Plot.cpp \
		build/moc_SLAM_Thread.cpp \
		build/moc_fastslam_1.cpp \
		build/moc_fastslam_2.cpp \
		build/moc_ekfslam_1.cpp
OBJECTS       = build/fastslam_core.o \
		build/qcustomplot.o \
		build/SLAM_Plot.o \
		build/SLAM_Thread.o \
		build/fastslam_1.o \
		build/fastslam_2.o \
		build/ekfslam_1.o \
		build/main.o \
		build/utils.o \
		build/moc_qcustomplot.o \
		build/moc_SLAM_Plot.o \
		build/moc_SLAM_Thread.o \
		build/moc_fastslam_1.o \
		build/moc_fastslam_2.o \
		build/moc_ekfslam_1.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		FastSLAM.pro
QMAKE_TARGET  = FastSLAM
DESTDIR       = 
TARGET        = FastSLAM

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: FastSLAM.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile FastSLAM.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile FastSLAM.pro

dist: 
	@$(CHK_DIR_EXISTS) build/FastSLAM1.0.0 || $(MKDIR) build/FastSLAM1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/FastSLAM1.0.0/ && $(COPY_FILE) --parents src/fastslam_core.h src/qcustomplot.h src/SLAM_Plot.h src/SLAM_Thread.h src/fastslam_1.h src/fastslam_2.h src/ekfslam_1.h src/utils.h build/FastSLAM1.0.0/ && $(COPY_FILE) --parents src/fastslam_core.cpp src/qcustomplot.cpp src/SLAM_Plot.cpp src/SLAM_Thread.cpp src/fastslam_1.cpp src/fastslam_2.cpp src/ekfslam_1.cpp src/main.cpp src/utils.cpp build/FastSLAM1.0.0/ && (cd `dirname build/FastSLAM1.0.0` && $(TAR) FastSLAM1.0.0.tar FastSLAM1.0.0 && $(COMPRESS) FastSLAM1.0.0.tar) && $(MOVE) `dirname build/FastSLAM1.0.0`/FastSLAM1.0.0.tar.gz . && $(DEL_FILE) -r build/FastSLAM1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_qcustomplot.cpp build/moc_SLAM_Plot.cpp build/moc_SLAM_Thread.cpp build/moc_fastslam_1.cpp build/moc_fastslam_2.cpp build/moc_ekfslam_1.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_qcustomplot.cpp build/moc_SLAM_Plot.cpp build/moc_SLAM_Thread.cpp build/moc_fastslam_1.cpp build/moc_fastslam_2.cpp build/moc_ekfslam_1.cpp
build/moc_qcustomplot.cpp: src/qcustomplot.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/qcustomplot.h -o build/moc_qcustomplot.cpp

build/moc_SLAM_Plot.cpp: src/qcustomplot.h \
		src/SLAM_Plot.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/SLAM_Plot.h -o build/moc_SLAM_Plot.cpp

build/moc_SLAM_Thread.cpp: src/SLAM_Thread.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/SLAM_Thread.h -o build/moc_SLAM_Thread.cpp

build/moc_fastslam_1.cpp: src/fastslam_core.h \
		src/utils.h \
		src/SLAM_Thread.h \
		src/fastslam_1.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/fastslam_1.h -o build/moc_fastslam_1.cpp

build/moc_fastslam_2.cpp: src/fastslam_core.h \
		src/utils.h \
		src/SLAM_Thread.h \
		src/fastslam_2.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/fastslam_2.h -o build/moc_fastslam_2.cpp

build/moc_ekfslam_1.cpp: src/fastslam_core.h \
		src/utils.h \
		src/SLAM_Thread.h \
		src/ekfslam_1.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/ekfslam_1.h -o build/moc_ekfslam_1.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: build/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) build/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

build/fastslam_core.o: src/fastslam_core.cpp src/fastslam_core.h \
		src/utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/fastslam_core.o src/fastslam_core.cpp

build/qcustomplot.o: src/qcustomplot.cpp src/qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qcustomplot.o src/qcustomplot.cpp

build/SLAM_Plot.o: src/SLAM_Plot.cpp src/SLAM_Plot.h \
		src/qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/SLAM_Plot.o src/SLAM_Plot.cpp

build/SLAM_Thread.o: src/SLAM_Thread.cpp src/SLAM_Thread.h \
		src/SLAM_Plot.h \
		src/qcustomplot.h \
		src/utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/SLAM_Thread.o src/SLAM_Thread.cpp

build/fastslam_1.o: src/fastslam_1.cpp src/fastslam_core.h \
		src/utils.h \
		src/SLAM_Plot.h \
		src/qcustomplot.h \
		src/fastslam_1.h \
		src/SLAM_Thread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/fastslam_1.o src/fastslam_1.cpp

build/fastslam_2.o: src/fastslam_2.cpp src/fastslam_core.h \
		src/utils.h \
		src/SLAM_Plot.h \
		src/qcustomplot.h \
		src/fastslam_2.h \
		src/SLAM_Thread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/fastslam_2.o src/fastslam_2.cpp

build/ekfslam_1.o: src/ekfslam_1.cpp src/fastslam_core.h \
		src/utils.h \
		src/SLAM_Plot.h \
		src/qcustomplot.h \
		src/ekfslam_1.h \
		src/SLAM_Thread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ekfslam_1.o src/ekfslam_1.cpp

build/main.o: src/main.cpp src/SLAM_Plot.h \
		src/qcustomplot.h \
		src/SLAM_Thread.h \
		src/fastslam_core.h \
		src/utils.h \
		src/fastslam_1.h \
		src/fastslam_2.h \
		src/ekfslam_1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/utils.o: src/utils.cpp src/utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/utils.o src/utils.cpp

build/moc_qcustomplot.o: build/moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_qcustomplot.o build/moc_qcustomplot.cpp

build/moc_SLAM_Plot.o: build/moc_SLAM_Plot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_SLAM_Plot.o build/moc_SLAM_Plot.cpp

build/moc_SLAM_Thread.o: build/moc_SLAM_Thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_SLAM_Thread.o build/moc_SLAM_Thread.cpp

build/moc_fastslam_1.o: build/moc_fastslam_1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_fastslam_1.o build/moc_fastslam_1.cpp

build/moc_fastslam_2.o: build/moc_fastslam_2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_fastslam_2.o build/moc_fastslam_2.cpp

build/moc_ekfslam_1.o: build/moc_ekfslam_1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_ekfslam_1.o build/moc_ekfslam_1.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

